In [1]:
import pandas as pd
from pandas import DataFrame, Series
import requests as re
from bs4 import BeautifulSoup
import datetime as date
import time


folder_adress = "C:/Users/Administrator/Desktop/stock_study/"


def market_index_crawling():
    Data = DataFrame()
    
    url_dict = {'미국 USD':'http://finance.naver.com/marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_USDKRW',
                '일본 JPY':'http://finance.naver.com/marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_JPYKRW',
                '유럽연합 EUR':'http://finance.naver.com/marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_EURKRW',
                '중국 CNY':'http://finance.naver.com/marketindex/exchangeDailyQuote.nhn?marketindexCd=FX_CNYKRW',
                'WTI':'http://finance.naver.com/marketindex/worldDailyQuote.nhn?marketindexCd=OIL_CL&fdtc=2',
                '국제 금':'http://finance.naver.com/marketindex/worldDailyQuote.nhn?marketindexCd=CMDT_GC&fdtc=2'}

    for key in url_dict.keys():
    
        date = []
        value = []

        for i in range(1,1000):
            url = re.get(url_dict[key] + '&page=%s'%i)
            url = url.content

            html = BeautifulSoup(url,'html.parser')

            tbody = html.find('tbody')
            tr = tbody.find_all('tr')

            '''마지막 페이지 까지 받기'''
            if len(tbody.text.strip()) > 3:
                
                for r in tr:
                    temp_date = r.find('td',{'class':'date'}).text.replace('.','-').strip()
                    temp_value = r.find('td',{'class':'num'}).text.replace(',','').strip()
            
                    date.append(temp_date)
                    value.append(temp_value)
            else:

                temp = DataFrame(value, index = date, columns = [key])
                
                Data = pd.merge(Data,temp, how='outer', left_index=True, right_index=True)        
                
                print(key + '자료 수집 완료')
                time.sleep(10)
                break

    Data.to_csv('%s/market_index.csv'%(folder_adress))
    return Data

K = market_index_crawling()

미국 USD자료 수집 완료
일본 JPY자료 수집 완료
유럽연합 EUR자료 수집 완료
중국 CNY자료 수집 완료
WTI자료 수집 완료
국제 금자료 수집 완료

In [2]:
import pandas as pd

df = pd.read_csv("C:/Users/Administrator/Desktop/stock_study/market_index.csv", index_col=0)
df

            미국 USD   일본 JPY  유럽연합 EUR  중국 CNY    WTI    국제 금
2004-04-12  1141.8  1074.13   1378.38  137.95    NaN     NaN
2004-04-13  1141.1  1082.12   1370.23  137.86    NaN     NaN
2004-04-14  1151.3  1072.87   1375.23  139.10    NaN     NaN
2004-04-16  1160.1  1070.20   1392.00  140.16    NaN     NaN
2004-04-19  1153.6  1069.63   1391.47  139.38    NaN     NaN
...            ...      ...       ...     ...    ...     ...
2020-12-31  1088.0  1056.11   1336.17  167.21  48.52  1893.1
2021-01-04  1082.5  1053.22   1330.77  167.93  47.62  1944.7
2021-01-05  1089.0  1059.24   1337.67  169.01  49.93  1952.7
2021-01-06  1086.5  1056.65   1340.69  168.78  50.63  1906.9
2021-01-07  1088.5  1052.96   1338.47  168.82    NaN     NaN

[4321 rows x 6 columns]